version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./svtechnologies:/var/www
      
  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "8080:80"
    volumes:
      - ./svtechnologies:/var/www
      - ./nginx/conf.d/:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - app